### PR TITLE
Implement hash object duplication

### PR DESCRIPTION
**Pull request by Xanewok**
Implements `Clone` for `Hash` via `BCryptDuplicateHash`.

Please let me know if you'd like me to address anything in the PR!

As a side note, I'm working on the Windows CNG API integration in the [Sequoia](https://gitlab.com/sequoia-pgp) OpenPGP implementation and this crate is very helpful - thanks for laying the groundwork. I'm filling the blanks as I go and if you don't mind I'll submit more patches separately if I find myself implementing extra stuff!

### CODE REVIEW

**Review by emgre — CHANGES_REQUESTED** [review]
I don't like `panic!` inside the library. Would be nice if there was a `TryClone` in the std, but apparently it does not exist.

Maybe we could write a `clone` method that returns a `crate::Result<Hash>` without implementing the `Clone` trait?

**Comment by Xanewok** [comment]
Rebased.

As much as I agree in principle on not panicking in the library, we should also only ever return errors that the user can reason about and act upon (a bit of an extreme example might be an infalliblle allocation API in Rust std library).

The C API is fallible, because the C caller can do multiple bad things:
- `STATUS_BUFFER_TOO_SMALL` - the user provided a smaller-than-expected buffer. We use the same object size as the object used to succesfully create the hash, so it must be okay,
- `STATUS_INVALID_HANDLE` - similar argument here, we know the handle wrapped is for the correct hash object, which is the reason for the safe Rust wrapper in the first place,
- `STATUS_INVALID_PARAMETER` - the function doesn't define any extra flags and we always pass a correct value (0).

This call is available on all CNG-supported OSes and the only way it can fail here is when the other library type-safe abstractions are wrong or the underlying CNG implementation is wrong, which in practice means that all bets are off for the user.

As always, the API design is all about trade-offs but I think that making cloning fallible to account for possible CNG bugs is not the right choice here.

**Comment by Xanewok** [comment]
Rebased and CI is green. Do you think we could land this as well?

**Review by emgre — APPROVED** [review]
I re-read `BCryptDuplicateHash` doc and you're right, if it fails, then something went really wrong and a panic is the way to go.

**Pull request merged**
