### PR TITLE
Mark all CNG handles as Send-safe

### PR DESCRIPTION
**Pull request by Xanewok**
cc @teythoon

### CODE REVIEW

**Comment by teythoon** [comment]
Thanks!  You created a patch faster than I could write the bug report :)

For context:  This is important to make them usable in async environments.  I'm working on https://gitlab.com/sequoia-pgp/sequoia/-/issues/615

**Comment by Xanewok** [comment]
Adding `Send` here should be safe - these handle wrappers all have corresponding destructors, if we clone structures we use a corresponding API call (e.g. `BCryptDuplicateHash` in `impl Clone for Hash`) and to the best of my knowledge these don't reference thread-local memory internally or anything of the sort. These should be safe to send to different threads.

I'm not 100% sure about `Sync`, though. As CNG states [here](https://docs.microsoft.com/en-us/windows/win32/seccng/cng-features#thread-safety): 

> Any functions that modify the same area of memory at the same time (critical sections) when being called from separate threads are not thread safe.

Thread safety disclaimer, as stated above, is somewhat cryptic. We don't know the implementation details and it might be possible that some innocent-looking CNG API calls that only accepts a handle can modify some CNG-internal buffer. If we had a `&self` method on a handle wrapper that would do something like that, while also sharing such a reference across threads, then we might find ourselves violating thread safety as described above.

It's worth noting that unique, mutable `&mut` references do not have this problem, as they're proven to be unique by the compiler, so `&mut` methods would be safe.

I think we should err on the safe side and if the user wants to have a `Sync`-implementing wrapper, they can always wrap it in a `Mutex` or other MT lock. Task systems usually care about futures being `Send` in order to send them between worker threads, so this PR enables exactly this use case and it should be safe to do so.

**Review by emgre — COMMENTED** [review]
We could add `Send` to:
- `AsymmetricAlgorithm`
- `Hash`
- `HashAlgorithm`
- `SymmetricAlgorithm`

and perhaps others too.

**Comment by Xanewok** [comment]
The Send and Sync traits are automatically implemented if all of the contained types implement this as well. Because `BCRYPT_*_HANDLE` types are effectively raw pointers and those are *not* considered Send/Sync, the requirement wasn't upheld before. Now other structs like `AsymmetricAlgorithm`, which contains `AlgoHandle` (rather than raw `BCRYPT_ALG_HANDLE`) should be automatically considered as Send/Sync as well.

I should add a test for that.

**Comment by Xanewok** [comment]
Added `Send` tests in https://github.com/emgre/win-crypto-ng/pull/35/commits/9b001b82e995290e7db8e1a4c187fc2a316512ea.

**Comment by teythoon** [comment]
It would be really good for us to fix this soon, because we want to make our 1.0 release on 2020-12-16, and this is blocking https://gitlab.com/sequoia-pgp/sequoia/-/issues/615

**Comment by Xanewok** [comment]
I can't approve/merge this myself

cc @emgre

**Review by emgre — APPROVED** [review]

**Comment by Xanewok** [comment]
@emgre thank you!

**Comment by Xanewok** [comment]
0.3.1 is now released containing this change: https://crates.io/crates/win-crypto-ng/0.3.1

**Comment by teythoon** [comment]
Sweet, thank you :)

**Pull request merged**
